// Mocks generated by Mockito 5.4.5 from annotations
// in flutter_voice_friend/test/widgets/app_bar_widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i2;
import 'dart:ui' as _i7;

import 'package:flutter_voice_friend/models/activity.dart' as _i4;
import 'package:flutter_voice_friend/services/user_service.dart' as _i6;
import 'package:isar/isar.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFuture_0<T1> extends _i1.SmartFake implements _i2.Future<T1> {
  _FakeFuture_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIsarCollection_1<OBJ> extends _i1.SmartFake
    implements _i3.IsarCollection<OBJ> {
  _FakeIsarCollection_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeActivity_2 extends _i1.SmartFake implements _i4.Activity {
  _FakeActivity_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Isar].
///
/// See the documentation for Mockito's code generation for more information.
class MockIsar extends _i1.Mock implements _i3.Isar {
  MockIsar() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
      ) as String);

  @override
  bool get isOpen => (super.noSuchMethod(
        Invocation.getter(#isOpen),
        returnValue: false,
      ) as bool);

  @override
  void requireOpen() => super.noSuchMethod(
        Invocation.method(
          #requireOpen,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.Future<T> txn<T>(_i2.Future<T> Function()? callback) =>
      (super.noSuchMethod(
        Invocation.method(
          #txn,
          [callback],
        ),
        returnValue: _i5.ifNotNull(
              _i5.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #txn,
                  [callback],
                ),
              ),
              (T v) => _i2.Future<T>.value(v),
            ) ??
            _FakeFuture_0<T>(
              this,
              Invocation.method(
                #txn,
                [callback],
              ),
            ),
      ) as _i2.Future<T>);

  @override
  _i2.Future<T> writeTxn<T>(
    _i2.Future<T> Function()? callback, {
    bool? silent = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #writeTxn,
          [callback],
          {#silent: silent},
        ),
        returnValue: _i5.ifNotNull(
              _i5.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #writeTxn,
                  [callback],
                  {#silent: silent},
                ),
              ),
              (T v) => _i2.Future<T>.value(v),
            ) ??
            _FakeFuture_0<T>(
              this,
              Invocation.method(
                #writeTxn,
                [callback],
                {#silent: silent},
              ),
            ),
      ) as _i2.Future<T>);

  @override
  T txnSync<T>(T Function()? callback) => (super.noSuchMethod(
        Invocation.method(
          #txnSync,
          [callback],
        ),
        returnValue: _i5.dummyValue<T>(
          this,
          Invocation.method(
            #txnSync,
            [callback],
          ),
        ),
      ) as T);

  @override
  T writeTxnSync<T>(
    T Function()? callback, {
    bool? silent = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #writeTxnSync,
          [callback],
          {#silent: silent},
        ),
        returnValue: _i5.dummyValue<T>(
          this,
          Invocation.method(
            #writeTxnSync,
            [callback],
            {#silent: silent},
          ),
        ),
      ) as T);

  @override
  void attachCollections(Map<Type, _i3.IsarCollection<dynamic>>? collections) =>
      super.noSuchMethod(
        Invocation.method(
          #attachCollections,
          [collections],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.IsarCollection<T> collection<T>() => (super.noSuchMethod(
        Invocation.method(
          #collection,
          [],
        ),
        returnValue: _FakeIsarCollection_1<T>(
          this,
          Invocation.method(
            #collection,
            [],
          ),
        ),
      ) as _i3.IsarCollection<T>);

  @override
  _i3.IsarCollection<dynamic>? getCollectionByNameInternal(String? name) =>
      (super.noSuchMethod(Invocation.method(
        #getCollectionByNameInternal,
        [name],
      )) as _i3.IsarCollection<dynamic>?);

  @override
  _i2.Future<void> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);

  @override
  void clearSync() => super.noSuchMethod(
        Invocation.method(
          #clearSync,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.Future<int> getSize({
    bool? includeIndexes = false,
    bool? includeLinks = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSize,
          [],
          {
            #includeIndexes: includeIndexes,
            #includeLinks: includeLinks,
          },
        ),
        returnValue: _i2.Future<int>.value(0),
      ) as _i2.Future<int>);

  @override
  int getSizeSync({
    bool? includeIndexes = false,
    bool? includeLinks = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSizeSync,
          [],
          {
            #includeIndexes: includeIndexes,
            #includeLinks: includeLinks,
          },
        ),
        returnValue: 0,
      ) as int);

  @override
  _i2.Future<void> copyToFile(String? targetPath) => (super.noSuchMethod(
        Invocation.method(
          #copyToFile,
          [targetPath],
        ),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);

  @override
  _i2.Future<bool> close({bool? deleteFromDisk = false}) => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
          {#deleteFromDisk: deleteFromDisk},
        ),
        returnValue: _i2.Future<bool>.value(false),
      ) as _i2.Future<bool>);

  @override
  _i2.Future<void> verify() => (super.noSuchMethod(
        Invocation.method(
          #verify,
          [],
        ),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);
}

/// A class which mocks [UserService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserService extends _i1.Mock implements _i6.UserService {
  MockUserService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get selectedLanguage => (super.noSuchMethod(
        Invocation.getter(#selectedLanguage),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#selectedLanguage),
        ),
      ) as String);

  @override
  set selectedLanguage(String? _selectedLanguage) => super.noSuchMethod(
        Invocation.setter(
          #selectedLanguage,
          _selectedLanguage,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get selectedSpeechToTextMethod => (super.noSuchMethod(
        Invocation.getter(#selectedSpeechToTextMethod),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#selectedSpeechToTextMethod),
        ),
      ) as String);

  @override
  set selectedSpeechToTextMethod(String? _selectedSpeechToTextMethod) =>
      super.noSuchMethod(
        Invocation.setter(
          #selectedSpeechToTextMethod,
          _selectedSpeechToTextMethod,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get selectedAudioBackend => (super.noSuchMethod(
        Invocation.getter(#selectedAudioBackend),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#selectedAudioBackend),
        ),
      ) as String);

  @override
  set selectedAudioBackend(String? _selectedAudioBackend) => super.noSuchMethod(
        Invocation.setter(
          #selectedAudioBackend,
          _selectedAudioBackend,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get selectedVoice => (super.noSuchMethod(
        Invocation.getter(#selectedVoice),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#selectedVoice),
        ),
      ) as String);

  @override
  set selectedVoice(String? _selectedVoice) => super.noSuchMethod(
        Invocation.setter(
          #selectedVoice,
          _selectedVoice,
        ),
        returnValueForMissingStub: null,
      );

  @override
  double get voiceSpeed => (super.noSuchMethod(
        Invocation.getter(#voiceSpeed),
        returnValue: 0.0,
      ) as double);

  @override
  set voiceSpeed(double? _voiceSpeed) => super.noSuchMethod(
        Invocation.setter(
          #voiceSpeed,
          _voiceSpeed,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get autoToggleRecording => (super.noSuchMethod(
        Invocation.getter(#autoToggleRecording),
        returnValue: false,
      ) as bool);

  @override
  set autoToggleRecording(bool? _autoToggleRecording) => super.noSuchMethod(
        Invocation.setter(
          #autoToggleRecording,
          _autoToggleRecording,
        ),
        returnValueForMissingStub: null,
      );

  @override
  int get level => (super.noSuchMethod(
        Invocation.getter(#level),
        returnValue: 0,
      ) as int);

  @override
  set level(int? _level) => super.noSuchMethod(
        Invocation.setter(
          #level,
          _level,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Activity get currentActivity => (super.noSuchMethod(
        Invocation.getter(#currentActivity),
        returnValue: _FakeActivity_2(
          this,
          Invocation.getter(#currentActivity),
        ),
      ) as _i4.Activity);

  @override
  set currentActivity(_i4.Activity? _currentActivity) => super.noSuchMethod(
        Invocation.setter(
          #currentActivity,
          _currentActivity,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get userInformation => (super.noSuchMethod(
        Invocation.getter(#userInformation),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#userInformation),
        ),
      ) as String);

  @override
  set userInformation(String? _userInformation) => super.noSuchMethod(
        Invocation.setter(
          #userInformation,
          _userInformation,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i2.Future<void> loadUserInformation() => (super.noSuchMethod(
        Invocation.method(
          #loadUserInformation,
          [],
        ),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);

  @override
  _i2.Future<void> saveUserInformation() => (super.noSuchMethod(
        Invocation.method(
          #saveUserInformation,
          [],
        ),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);

  @override
  _i2.Future<void> updateUserInfo(Map<String, dynamic>? userInfo) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserInfo,
          [userInfo],
        ),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);

  @override
  void updateCurrentActivity(_i4.Activity? activity) => super.noSuchMethod(
        Invocation.method(
          #updateCurrentActivity,
          [activity],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
